name: strongR-frida-build

on:
  workflow_dispatch:

jobs:
  android_build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r25b

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential ninja-build flex bison python3-pip -y
        python3 -m pip install lief

    - name: Clone Frida
      run: |
        git clone --recurse-submodules https://github.com/frida/frida

    - name: Build Android arm64
      run: |
        cd frida
        ./configure --host=android-arm64
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frida-android-arm64
        path: frida/build/subprojects/frida-core/server/frida-server
